sudo: false
language: node_js
node_js:
  - 6
  - 7
  - 8

before_install:
# Get installer script.
  - wget https://github.com/nodeGame/nodegame-test/raw/master/nodegame-installer.js
  - chmod a+x nodegame-installer.js

install:
  - node nodegame-installer.js @dev --install-dir node_modules --no-spinner --branch v4
  - npm install -g should
  - npm install -g mocha

script:
# Add extra tests here.

# Test Ultimatum game.
  - cd node_modules/nodegame-test/games/ultimatum-game
  - ./bin/run-standalone-test-v4.sh
